name: Correct Records

on:
  # Manual trigger from the Actions UI
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      # your CASE_SEARCH_URL in Settings → Secrets
      DB_CONN: ${{ secrets.MONGODB_CONNECTION_STRING }}
      URL: ${{ secrets.CASE_SEARCH_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          echo "Installing Python dependencies..."
          python -m pip install --upgrade pip
          # Check if requirements.txt exists before trying to install from it
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            echo "Python dependencies installed from requirements.txt."
          else
            echo "requirements.txt not found, skipping pip install."
          fi

      # Add this step to install Playwright browsers and dependencies
      - name: Install Playwright Browsers and Dependencies
        run: |
          echo "Installing Playwright browsers..."
          # Installs default browsers (Chromium, Firefox, WebKit) and OS dependencies
          playwright install --with-deps
          # If you ONLY need Chromium, you can uncomment the line below and comment out the line above
          # playwright install --with-deps chromium
          echo "Playwright browsers installed."

      # Add a step to run your actual Python script
      # Replace 'main.py' with the actual name of your script if different
      - name: Run script
        run: |
          echo "Running Python script..."
          python CorrectDockets.py $DB_CONN $URL
          echo "Script finished."
